# Generated by Django 4.2.6 on 2023-11-23 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('ideItemMenu', models.BigAutoField(primary_key=True, serialize=False)),
                ('strLink', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblItemMenu',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('ideLanguage', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('strLanguage', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblLanguage',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('ideTranslation', models.BigAutoField(primary_key=True, serialize=False)),
                ('strTranslation', models.TextField(unique=True)),
                ('strLabelKey', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblTranslation',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('ideUserType', models.BigAutoField(primary_key=True, serialize=False)),
                ('strUserType', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tblUserType',
            },
        ),
        migrations.CreateModel(
            name='UserTypeHasItemMenu',
            fields=[
                ('ideUserTypeHasItemMenu', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('ideItemMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemmenu')),
                ('ideUserType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertype')),
            ],
            options={
                'db_table': 'tblUserTypeHasItemMenu',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ideUser', models.BigAutoField(primary_key=True, serialize=False)),
                ('strUserName', models.CharField(max_length=255)),
                ('strEmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('ideUserType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usertype')),
                ('strDefaultLanguage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language')),
            ],
            options={
                'db_table': 'tblUser',
            },
        ),
        migrations.AddField(
            model_name='language',
            name='ideTranslation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.translation'),
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='ideTranslation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.translation'),
        ),
    ]
