# Generated by Django 4.2.6 on 2023-12-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usertypehasitemmenu_ideusertypehasitemmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='ideTranslation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation', to='api.translation'),
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('ideLogError', models.BigAutoField(primary_key=True, serialize=False)),
                ('strAddress', models.TextField()),
                ('strAppOrigin', models.CharField(max_length=255)),
                ('strParameters', models.TextField()),
                ('strError', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('ideUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'tblLogError',
            },
        ),
        migrations.CreateModel(
            name='LogAccess',
            fields=[
                ('ideLogAccess', models.BigAutoField(primary_key=True, serialize=False)),
                ('strAddress', models.TextField()),
                ('strEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('strResult', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('ideUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'tblLogAccess',
            },
        ),
    ]
